language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn deploy -X --settings travis_settings.xml

env:
  global:
    - secure: "CDO2VNKgMS+oJiRD2I93SSKaA9sLvLTjrWMa6YlD6y90OHI9q3ajiKepJc9ejxkOVN0PEX9K88DANO3AF2LgkvfliW8qswOrOXav3QzNfAJxhjpkrGufv95hGNhk5h05SARxGL+/MqwrNUQcZnko3Gmt4LvIlEFAW1ZKE3NNdJmq5Q2UOAnyuyNUkFMDcEHdnVKsNn0T8BUi3wCp4aqsO794tVMi+oYAeFlQPSCktHmDtlDsAr9i+Qpi7Lr0DZaWN6+X0N+icivRrUvVwsWJqvbYGtElgeAFbrh6yVLPKawOrWUZzi5XYNPwR1XKQT0PQW9YGtWbvK0cqDc30HFGbs8OXQAy6pH9abU60J+qY+oBEls1eqzynSxxDi0bu5TM2Md9SR64yBlNPD7wu2jdxRjdbcF2tpBLzhEnQrC+yhfR+w3laIzKVX/BXkqPcD6z6hLYDeXZdwrwff06vimAodGd7SJ0NvpEUgHrKqreGuASjCI8aePE9Y1IbxP5daNCprXVTe0kwLM9CcARvPQEAZvnYpcYsNbesgX/CbSdIybvFbdO/9mZ/waIXN5ZYQJOXeqRIIVPk02Pl2Kj+SkDv4N9PaxhrHQAUop/p15Ysplz8ggRMYhD/4Te3DAB+r3B4y7YPZXssllilxbIG5Wr3ZMgUXxBLzwjJck43PXHjQw="
    - secure: "lLlbfHSmFW/wp6eM6wQe1kv6VGzgfKyhC0ETOLSWvfT54t4gG1ZXG1mNPxKAhO+KmLtU5okDMq5xiS7kpxWIdMl4m/dfAFqkZ2a/HcsdPgxe2nM2233Ir8jVS3FVCfrTMblUZSzt66LVH9voaFCHUv1G7nBbnzZIuemLMqlrf8/TId+YGz4poPTNKnjnLGbf8IRa8kzKb23jepdC/eH8OBeKWGdcO1dDI5yskJWmMZfgyfJb0AMbfnvlU+m52wib+q/TnKvbqMsXN76H1E1Nkx8fmYk5R3LtuyDdTNMVhOemMwZsZrGoNKNWux61z2dCY/CSay/Lfpr0An1IcGHmnOS4iR0xcxivNH7MndmRvA5DKDL3azK4TVuTotQbyQ9BuTajGsWmOkdiIUMSn2EXLQAKcF/L4qWyqH2ydOO1m81HXauGcZSdbJBpI6RxkMTA92chfKBw4YxIDP8itCLzjC2kqY3crZed7YsBGRNLyNK9kAsLaOJS96KaZCaR2pMsXG8fDyi2GBugFht4wJhsIyhGegoKuo3Im2C1tfZaUebD0mWhGPw54wjfE9fozivhdo36dS2DIr274AR1dhM5cA6UUlC2sWIhAYndOXfvBUDItGTiBJJ3pf7p834ovLd/um3OEkfwlMloMlEzqiV9+wG0lDO77iSORP7ydGP+g8Y="
