language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean verify

after_success: mvn deploy --settings travis_settings.xml

env:
  global:
    - secure: "Ysh895U3st9McxdgMmnN4Ak25FXuvkjaRQCnHvGxRNkwfaUGpsqZRns9h/3BkXa+zLKdFgCfiLsRqDT46qNagsUhayrTinog/AUJJG5t7nxZIAUfxXwwA/nhKgCBlaNqC6WCK2xxz3R7l9JpCKYSONeCEtzF6BtY/0BVz23FslZHJ+0K9F+/UdDOCgmAd7kkT/L9XwqkUys4g1HcIh/3/rIxmqSvsQg7wC7CE3g+Ctoc9BuL+tDpOiT0y8c032YhhETMiPd07WsxaWJp4e9NKvvDjsUgVLwiKfsfHTX2JUSpHEVmal78kY2r4G15jIMrk1Ha6DViECqVzf5zd84cDtb5tMMllgbZHloz15juciaOxEPR/P8XiqAdn5QOR5hxU+14E36rPHuVJ/NQS16OV5Fyr81iDv3dVK1SLETNXCeyONgBilvuLaD59GKAYq13sCisTJfTqzyYl9drFTa+CueX47tujjWuQYe9HHKb67X75JfSM6f1FhZcSBUjJA8jgm5iM4oHeVszi1ERBjeMwRMyK7zniZcxGhvCIEjJ5gOrcoJAz0sij6vkVxjb9UJzo6aU0xiUcmYdPQIoem3Cjzsm/ehdbgwHM2g+ptrM3Kph7WYVHxcrcxQvIWkUBk2Pnrqe1rbaazp6n0nKEJI2HVw0ygahAuNsqUhtwUx9kJI="
    - secure: "lGBUit0EYaxWU0He8N+2DpmBplzDqIStWhWFHEYBw/IhvpwUNXfyyqPHeJmRwXrQAYsqac3s+cKsuNUXS0tSQk1B6Gnp4FPakv5daPF/kUwzaTjPhCcB4jaUX7xE8FagmLt3scb9/jWlDm1kjqsAf933XWue+LArC6TrMhbhEhjVBdER4DeTn7CBBDvoo6Sj08pT0U+awGXQj4AW/3IncYcxouUN6/lvSBtVabcJw9IGyDYzBv99nMoYWU13lR62o8RvF5KbjHUbxPVI71HMyRDP+8F7NGFVZ2bhTCYG+lu2ydRIabJLFxJZxBz3TSuTEbOLMxtC4+YKgkDKh9JUrEcuAcBiWAOqXjEF9LzNvVmrcBPGBt8KqRyk/NFdIkYH/OCniSJ0Df7LEDgKE6+5I0caXnFGEo/3F8crkPEhBaSxfSDYFfDOrOFQYYTtDWbvXUoh3xEbXl8YXK7Y+IXPBwlcMbpSsN/GHpTC7veNBoSJ65rsItrFRx3eXV3IMCtvhQyK0XAJolXZNPt2Z1MJMu/ocWCGP7XIWXE47AsFd4FfRFY+vXwLHJj77RQYcYtmCWr0qF9DGZoEcSIAnursKjkcmLWPx30wL69odzJUa1rHHmvV2G3Jt1IPnQcBjgBk7bc7HBPOC6Zj9H5CzlGJGH+jm21UKYEy0+OfxPQbgeM="
